const GAME_CONFIG = {
  gridConfig: {
    availableSpots: [
      { row: 0, col: 0, cost: 0 },
      { row: 0, col: 1, cost: 0 },
      { row: 0, col: 2, cost: 8 },
      { row: 0, col: 3, cost: 15 },
      { row: 1, col: 0, cost: 3 },
      { row: 1, col: 1, cost: 5 },
      { row: 1, col: 2, cost: 15 },
      { row: 1, col: 3, cost: 25 },
      { row: 2, col: 0, cost: 25 },
      { row: 2, col: 1, cost: 50 },
      { row: 2, col: 2, cost: 100 },
      { row: 2, col: 3, cost: 150 },
      { row: 3, col: 0, cost: 200 },
      { row: 3, col: 1, cost: 250 },
      { row: 3, col: 2, cost: 300 },
      { row: 3, col: 3, cost: 350 },
      { row: 4, col: 0, cost: 450 },
      { row: 4, col: 1, cost: 500 },
      { row: 4, col: 2, cost: 600 },
      { row: 4, col: 3, cost: 700 },
    ],
  },
  animalTypes: {
    Egg: { sellPrice: 0, mergeTo: "Mantis" },
    Mantis: { sellPrice: 1, mergeTo: "Mantis2" },
    Mantis2: { sellPrice: 2, mergeTo: "CatEgg" },
    CatEgg: { sellPrice: 0, mergeTo: "Cat" },
    Cat: { sellPrice: 5, mergeTo: "Cat2" },
    Cat2: { sellPrice: 10, mergeTo: "Cat3" },
    Cat3: { sellPrice: 25, mergeTo: "PandaEgg" },
    PandaEgg: { sellPrice: 0, mergeTo: "Panda" },
    Panda: { sellPrice: 50, mergeTo: "Panda2" },
    Panda2: { sellPrice: 100, mergeTo: "Panda3" },
    Panda3: { sellPrice: 200, mergeTo: "Panda4" },
    Panda4: { sellPrice: 400, mergeTo: "VultureEgg" },
    VultureEgg: { sellPrice: 0, mergeTo: "Vulture" },
    Vulture: { sellPrice: 800, mergeTo: "Vulture2" },
    Vulture2: { sellPrice: 1600, mergeTo: "Vulture3" },
    Vulture3: { sellPrice: 3200, mergeTo: "Vulture4" },
    Vulture4: { sellPrice: 6400, mergeTo: "Vulture5" },
    Vulture5: { sellPrice: 12800, mergeTo: "EndDemoAnimal" },
    EndDemoAnimal: { sellPrice: 25600, mergeTo: null },
  },
  animalImages: {
    Egg: "images/egg.png",
    Mantis: "images/mantis-1.png",
    Mantis2: "images/mantis-2.png",
    CatEgg: "images/cat-egg.png",
    Cat: "images/cat-1.png",
    Cat2: "images/cat-2.png",
    Cat3: "images/cat-3.png",
    PandaEgg: "images/panda-egg.png",
    Panda: "images/panda-1.png",
    Panda2: "images/panda-2.png",
    Panda3: "images/panda-3.png",
    Panda4: "images/panda-4.png",
    VultureEgg: "images/vulture-egg.png",
    Vulture: "images/vulture-1.png",
    Vulture2: "images/vulture-2.png",
    Vulture3: "images/vulture-3.png",
    Vulture4: "images/vulture-4.png",
    Vulture5: "images/vulture-5.png",
    EndDemoAnimal: "images/enddemo-animal.png",
  },
  purchaseConfig: {
    Egg: { cost: 0, unlocked: true },
    CatEgg: { cost: 7, unlocked: false },
    PandaEgg: { cost: 20, unlocked: false },
    VultureEgg: { cost: 50, unlocked: false },
  },
  coopConfig: {
    cat: {
      buyCost: 10,
      producesType: "CatEgg",
      baseTime: 30,
      timeReductionFactor: 0.95,
      upgradeCostMultiplier: 3,
    },
    panda: {
      buyCost: 40,
      producesType: "PandaEgg",
      baseTime: 60,
      timeReductionFactor: 0.95,
      upgradeCostMultiplier: 3,
    },
    vulture: {
      buyCost: 120,
      producesType: "VultureEgg",
      baseTime: 120,
      timeReductionFactor: 0.95,
      upgradeCostMultiplier: 3,
    },
  },
  autoMergeConfig: {
    buyCost: 1,
    baseInterval: 10,
    intervalReductionFactor: 0.9,
    animalRequirements: [0, 6, 15, 30, 45, 65, 90, 115],
    glowTriggerTimes: [2, 1, 0.5, 0.25],
  },
  shuffleConfig: {
    buyCost: 10,
    delayAfterAutoMerge: 250,
  },
  animationConfig: {
    wiggleInterval: 3000,
    wiggleDuration: 1000,
    spawnAnimationDuration: 600,
    slaughterAnimationDuration: 1000,
    mergeExplosionDuration: 800,
    achievementDuration: 3000,
    floatingNumberDuration: 1000,
    particleCount: 20,
    autoMergeGlowDuration: 500,
    autoMergeGlowClearDelay: 1500,
    processingSpinDuration: 2000,
    processingParticleInterval: 200,
    processingParticleLifetime: 1000,
    processingBurstDuration: 800,
    coinFlyDuration: 1000,
    coinFlyDelay: 50,
    moneyValueFadeDuration: 2000,
  },
};
